openapi: 3.0.0
info:
  title: User API
  description: Simple RESTful API in Node.js
  version: 0.0.1
servers:
  - url: http://localhost:8080/api
    description: Local server
tags:
  - name: Users
    description: API for in the system
paths:
  /users:
    get:
      tags:
        - Users
      summary: Return all users with list.
      description: Return all existed users.
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      properties:
        id:
          type: integer
          format: int64
          example: 1
        username:
          type: string
          example: Jimmy
        email:
          type: string
          example: test@test.com
      required:
        - id
        - username
        - email
